### ISSUE TITLE
readme.txt should list more important features

### ISSUE THREAD

**Issue by glueckpress** [inpsyde/multilingual-press#106]
The readme.txt should list important features such as 

* SEO-friendly URLs & Permalinks
* Top-level Domains per Language
* Automatic `hreflang` support for language sites

While these features may be more or less taken for granted by developers, users focussed more on marketing and SEO will [look for them](https://twitter.com/luckyboost/status/588648981623742464) in the features listed.

**Comment by bueltge** [comment]
Thx. The readme has the update, but we should check this again on the next release. Closed for this topic.
