### ISSUE TITLE
Missing Options when switching from 2.1 Free to 2.2

### ISSUE THREAD

**Issue by toscho** [inpsyde/multilingual-press#109]
When someone switches from version 2.1.2 Free to to Pro or 2.2, the options for MultilingualPress are not there, so the Metaboxes for post translations don’t show up at all.

**Comment by bueltge** [comment]
Clean install, MLP Free 2.1.2
Set all settings, relationships etc.
Update to the current master of this repo.
Done, no problems or issues. 

Maybe helpful a hint in the readme, changelog, that all users now have a additional menu item for new features in Network settings - MultilingualPress
