### ISSUE TITLE
Alternative Site Name in WP Admin Bar

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingual-press#110]
It is not easy in some user installs to identify the right site for each language. It would be helpful, it is possible the Alternative Title would be use in the Site Name of the Admin Bar.

Currently helps this plugin.
https://gist.github.com/bueltge/7abfbfc65f1f19a782cc

But, will we add this to the core. The result is a optional settings or not? Or we use it always, if is set in the settings to each site?

**Comment by bueltge** [comment]
From directly discussion. Is not a option for the core, overhead and additionals for settings. We will rewrite the add on to use the MLP API and done, ready to use.

see http://make.marketpress.com/multilingualpress/2015/02/how-to-get-translations-programmatically/

**Comment by bueltge** [comment]
New discussion for feature in MLP Core.

**Comment by bueltge** [comment]
After we release this new feature, we should remove the add-on from the wiki.

**Comment by bueltge** [comment]
Ready to merge via #182

**Comment by tfrommen** [comment]
Closed in https://github.com/inpsyde/multilingual-press/commit/fb0478765701b65a16841e8dff5d67c3e7451fc8.
