### ISSUE TITLE
Cyrillic, escaping url and lowercases

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingual-press#111]
An issue with my cyrillic URL, testing required.

The cyrillic URL are encoded in lowercase and the automated link from MLP is in lowercase as well.
When it's copy paste a cyrillic URL in the address bar, the encoded url is capitalized and returns a 404.

Here is what wikipedia says on that topic :
>Capitalizing letters in escape sequences. All letters within a percent-encoding triplet (e.g., “%3A”) are case-insensitive, and should be capitalized. Example: http://www.example.com/a%c2%b1b → http://www.exa

**Comment by toscho** [comment]
The lowercase URLs are built by WordPress, not by MLP. Look at the page slug in the posts table, they are already stored as such. This is not our bug.

It should work nevertheless, no matter what case is used. However, you can enforce uppercase permalinks with:

```php
<?php # -*- coding: utf-8 -*-
/**
 * Plugin Name: T5 Uppercase Encoded Permalinks
 *
 * @version 2015.05.02
 * @author  toscho
 * @license MIT
 */

/**
 * @param string       $permalink Pre-composed URL.
 * @param \WP_Post|int $post Some hooks pass a WP_Post object, some just an ID.
 *                           Thank you WordPress.
 * @return string
 */
function t5_uppercase_encoded_urls( $permalink, $post ) {

	$post = get_post( $post );
	$raw = rawurldecode( $post->post_name );

	if ( $raw === $post->post_name )
		return $permalink;

	return str_replace( $post->post_name, rawurlencode( $raw ), $permalink );
};

add_filter( 'post_link',       't5_uppercase_encoded_urls', 10, 2 );
add_filter( 'page_link',       't5_uppercase_encoded_urls', 10, 2 );
add_filter( 'post_type_link',  't5_uppercase_encoded_urls', 10, 2 );
add_filter( 'attachment_link', 't5_uppercase_encoded_urls', 10, 2 );
```

**Comment by bueltge** [comment]
Yes, I have seen this in the core. But it is helpful that we expand the core via plugin in this topic? The topic should a issue on the core.

**Comment by toscho** [comment]
I cannot even reproduce the 404 locally. We should not cover it in our code. This is not related to MLP or multisite.

**Comment by bueltge** [comment]
:+1: my Opinion, not  a topic for MLP.
