### ISSUE TITLE
Missing hfreflang attribute for content's own language

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#114]
In `Mlp_Hreflang_Header_Output::wp_head()` resp. `Mlp_Hreflang_Header_Output::http_header()` 
only the available translations are searched - excluding the current base content.
That should be included, though :
```
If you have multiple language versions of a URL, each language page must identify all language
versions, including itself.  For example, if your site provides content in French, English, and Spanish,
the Spanish version must include a rel="alternate" hreflang="x" link for itself in addition to links to the
French and English versions. Similarly, the English and French versions must each include the same
references to the French, English, and Spanish versions.
```
https://support.google.com/webmasters/answer/189077?hl=en

So maybe `Mlp_Hreflang_Header_Output::get_translations()` should pass   `array( 'include_base' => TRUE )` when fetching the available translations:

https://github.com/inpsyde/multilingual-press/blob/36d312c80c053e4932282df401cd2a776d285511/inc/hreflang-header/Mlp_Hreflang_Header_Output.php#L98

**Comment by tfrommen** [comment]
Tested, works, closed with f0b6e57d6dd997fba39d546b555ffd8c8c883405.
