### ISSUE TITLE
Make <html lang=""> attribute reflect MLP language

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#118]
Currently, the language attribute on the HTML tag is governed by the site's language setting under ```Settings->General->Site Language```

When using MLP, this may not be the expected behaviour. 
MLP should expose the site as the language it is configured for, including the <html lang=""> attribute.
This should not be decided by the locale WordPress has used to translate its strings

**Comment by tfrommen** [comment]
Closed with 31fa2a6b3e8e856ae116743d00ab0396c16df249.

**Comment by toscho** [comment]
https://github.com/inpsyde/multilingual-press/commit/31fa2a6b3e8e856ae116743d00ab0396c16df249 is not related to this issue at all.
