### ISSUE TITLE
Add post slug field to Advanced Translator

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#119]
Apart from content and title, users might want to be given control over the remote post's slug as well, directly within the translation metabox.

I don't think this request ventures too far into the territory of "custom fields and why we don't do them automatically" and it would fill in another gap to giving users almost the same experience when translating a post

**Comment by tfrommen** [comment]
Closed with d638c44b7010eab669d0e3e3977c3aa0f07843b4.
