### ISSUE TITLE
Do not redirect while DOING_AJAX

### ISSUE THREAD

**Issue by dboune** [inpsyde/multilingual-press#121]
I found it necessary in one circumstance to hook `mlp_redirect_url` and prevent redirects during an XHR.

Specifically this occurs with plugins that do not use `wp-admin/admin-ajax.php` to provide data to the front end. The case here was the use of the Infinite Scroll plugin, part of Jetpack.

You can see the code I am referring to here:
https://github.com/Automattic/jetpack/blob/3.5.3/modules/infinite-scroll/infinity.php#L596-L614

In any case, I believe the definitive determination of whether or not we are in an ajax call should be when `DOING_AJAX` is `true`, not `is_admin()`. It's possible to handle XHR outside of `wp-admin/admin-ajax.php`, and at the very least DOING_AJAX should be set if you care for other code to be able cope with it.

**Comment by tfrommen** [comment]
Hi,

so, what are you suggesting? That's one of the reasons we provide filters and actions. :)

**Comment by toscho** [comment]
This shouldn't happen. The redirect is disabled when `is_admin()` is `true`. The file `wp-admin/admin-ajax.php` always runs in admin mode. Can you please provide the code to reproduce the problem?

**Comment by dboune** [comment]
I apologize for the thin report. I've updated the issue above. I was very glad to find the filter there, which allowed me to fashion a quick workaround, so thank you very much for having thought of that potential.

**Comment by dboune** [comment]
Now that I pause a moment.. I can see that you would likely need to do both tests, since you wouldn't want to redirect users within of the admin area in *any* case. I'm sure that was apparent to you, but I thought I'd mention that it did just now occur to me.

**Comment by toscho** [comment]
Oh, they are circumventing the regular API by using some custom AJAX response. Dirty, but yes, we can fix that.

The regular admin area will [never be redirected](https://github.com/inpsyde/multilingual-press/blob/1c21a5c2b6b653aed0c623cef2b05774d0621925/inc/redirect/Mlp_Redirect.php#L60).

**Comment by dboune** [comment]
Yes, I assume they have their reasons, though I can't say what they are. It's an automatic project, so I'll grudgingly give them the benefit of the doubt.

Very good. That certainly continues to be desirable.

**Comment by tfrommen** [comment]
Hi Damian,

I just pushed a [commit to a separate issue branch](https://github.com/inpsyde/multilingual-press/tree/issue/121_redirect).
By default, AJAX requests will not be redirected anymore, no matter if `admin-ajax.php` or not (as long as `DOING_AJAX` is set to `TRUE`).
In case one actually would want the request redirected, there's a new filter `mlp_redirect_frontend_ajax`.

Testing welcome. :)

**Comment by toscho** [comment]
@tfrommen I cannot think of any case where an AJAX request should be redirected. Better wait until someone provides a use case before you widen the API.

**Comment by tfrommen** [comment]
@toscho so you would just leave out the filter/variable, right?

**Comment by toscho** [comment]
Yes. The API should cover known use cases only. That makes it easier to change the code later.

**Comment by dboune** [comment]
Thanks for the quick action! I'll test out the feature banch later today.

**Comment by dboune** [comment]
Tested and working!

**Comment by tfrommen** [comment]
Hi Damian,

thanks for testing/confirming. The branch has been merge into `master` already.

Closed with 4ed1cb94b1a9e4bb496b202d139932b079e7d63a.
