### ISSUE TITLE
Missing languages after installing 2.2 master-27774e1723

### ISSUE THREAD

**Issue by dnauck** [inpsyde/multilingual-press#126]
I'm using a multi site wordpress installation 4.2.2 and downloaded the repository as zip file rev 27774e1723 -> install plugin -> upload as zip -> active for all sites.

The plugin installer print out a success messages, but i et the following message on the setting -> language manager page:

```No items found. We recommend to reinstall this plugin.```

Looks like the plugin is missing to import the data of its table. What can i do?

**Comment by tfrommen** [comment]
Which version of MultilingualPress did you have installed before? FREE or Pro?

**Comment by dnauck** [comment]
Neither.

Never used this plugin before.

**Comment by tfrommen** [comment]
Sorry, there was a bug - which is fixed already.

Could you please check if the [ZIP of the according issue branch](https://github.com/inpsyde/multilingual-press/archive/issue/126_missing_languages.zip) does the trick for you as well?

Thanks,
Thorsten

**Comment by dnauck** [comment]
Hi @tfrommen, this fix solved the issue with the missing languages for me. Thank you very much for your fast response/fix.

**Comment by tfrommen** [comment]
Thanks for testing/confirming. The branch has now been merged into the master.

Closed with 49ab79efb28ca21d1ef0a98086718db6bd87f1c5.
