### ISSUE TITLE
Compatibility with Enfold theme

### ISSUE THREAD

**Issue by dnauck** [inpsyde/multilingual-press#127]
Using the new 2.2 (master 49ab79efb28ca21d1ef0a98086718db6bd87f1c5) version and tested a page with the Enfold 3.2.2 (Wordpress 4.2.2) theme:

Add new site to network, linked with existing page -> site generator displayed success message.

I've the following issues:

* not all css is loaded properly (most of the chosen theme style css)  
* images are missing (strangely only ~70% of them are missing (or defect))
* the ```Avia Layout Architekt``` is not used in the translation boxes (so i do not see any translation there)

**Comment by tfrommen** [comment]
Sorry for the seemingly stupid question, but does everything work as expected if you deactivate MultilingualPress and visit the according blog on the frontend? So far, we are unaware of any problems with assets/resources...

**Comment by tfrommen** [comment]
@dnauck any news on this?
