### ISSUE TITLE
Add confirmation to post saving when relationships were changed

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#131]
When the user changed the post relationships, the "Save and Reload" button beneath these settings needs to be clicked in order to apply the changes.

When the post itself is saved, the changes are discarded. There is a text indicating this, but I feel we should be more active about this:

 * When the relationships are changed, set a new variable hasChanged/isDirty/whatEver to 1
 * When relationships are saved, set it to 0 again.
 * When a post is saved, check this variable and make the user confirm his action if there are pending changes to the post relationships

**Comment by tfrommen** [comment]
Closed with f473c5e259284044ddb6f11eeb69a81c0df38d4d.
