### ISSUE TITLE
Sneaky notice in Mlp_Translation.

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#132]
There have been reports of a ```Notice: Undefined index: icon in wp-content/plugins/multilingual-press/inc/types/Mlp_Translation.php on line 63```

This can happen if the config array is missing the 'icon' element.

In [Mlp_Language_Api:L326-L340](https://github.com/inpsyde/multilingual-press/blob/master/inc/language-api/Mlp_Language_Api.php#L326-L340), the 'icon' element is only set when 'http_name' is not empty:

```php
if ( '' !== $data[ 'http_name' ] ) {
		$arr[ 'icon' ] = $this->get_flag_by_language(
			$data[ 'http_name' ],
			$site_id
		);
	}
```

An easy fix would be to ensure the 'icon' element is set in any case.

**Comment by tfrommen** [comment]
Closed with 89930115ffc587dd476623ac80a158b581d3bea3.
