### ISSUE TITLE
No-Redirect links don't properly set session to not redirect

### ISSUE THREAD

**Issue by dboune** [inpsyde/multilingual-press#138]
When clicking on a language specific link with `?noredirect=LANG` a PHP session is created which appears to intend to keep further redirects for the given language site from occurring during that session. The result is unexpected, as redirects still occur wherever they would without the session.

I would also like to recommend that it would be better to follow the WordPress standard of using non PHP session cookies to handle. This would allow for caching solutions to be better configured.

**Comment by Biont** [comment]
Thanks you for creating the issue. We have only recently become aware of this problem and are getting a fix ready.

**Comment by tfrommen** [comment]
Closed with 32d4328eb5759f9aae4a56cd9612dc1bbd1ecc6b.
