### ISSUE TITLE
Trying to get property of non-object in /wp-content/plugins/woocommerce-german-market/inc/WGM_Settings.php

### ISSUE THREAD

**Issue by Giede** [inpsyde/multilingual-press#142]
Ich habe alles nach Standard installiert. Im Reiter "Preis pro Einheit" bei der Produktpflege erscheinen Fehlermeldungen - siehe Screenshot.

![bildschirmfoto 2015-08-03 um 16 31 57](https://cloud.githubusercontent.com/assets/12229674/9039709/88aab922-39fd-11e5-849a-3d71e25b63fb.png)

**Comment by tfrommen** [comment]
@Giede what exactly does this have to do with MultilingualPress? ;)

**Comment by Giede** [comment]
@tfrommen ups! sorry, wrong project. ;-)
