### ISSUE TITLE
Improve the composer.json: enhance description, add support information

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/multilingual-press#146]
Suggestion about a more brief description from @toscho:

> Create a fast translation network on WordPress multisite.
> Run each language in a separate site, connect the content in a lightweight user interface. 
Optionally 
> Pull requests are welcome: https://github.com/inpsyde/multilingual-press

Add some missing [support](https://getcomposer.org/doc/04-schema.md#support) fields:
 * `issues` → https://github.com/inpsyde/multilingual-press/issues
 * `forum` → https://wordpress.org/support/plugin/multilingual-press
 * `source`  → https://github.com/inpsyde/multilingual-press
 * `wiki` → https://github.com/inpsyde/multilingual-press/wiki
 * `docs` → ? 

I'm not sure if the link to the developer blog (http://make.marketpress.com/multilingualpress/) should go into the `support:docs` field or should just be mentioned in the `description` text.

**Comment by toscho** [comment]
The developer blog is not for support, it is more like a live documentation – that was the idea at least, nobody is writing there currently. The docs are here: https://marketpress.com/documentation/multilingual-press/

**Comment by kraftner** [comment]
I wonder if for the forum it might be nice to add the Helpdesk. Not sure if the composer spec allows multiple forums or just one value.

https://marketpress.com/support/forum/multilingual-press/

In any case it is a forum and a nice way to promote your support offering.

**Comment by tfrommen** [comment]
Closed with 4c60e4446fc90428f792bccd8e0cb65023c86f05.
