### ISSUE TITLE
Upgrade notice not applicable any more

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#147]
After the merge of Free and Pro are completed displaying an upgrade notice doesn't make any sense no more.

I am talking about this message:

> In MultilingualPress Pro, you can edit the translation right here, copy the featured image, set tags and categories, and you can change the translation relationship.

Here you check if the plugin name is `MultilingualPress Pro` and show the notice otherwise.

https://github.com/inpsyde/multilingual-press/blob/master/inc/post-translator/Mlp_Translation_Metabox.php#L309-L313

In the Pro version the callbacks are removed so the notice doesn't show.

https://github.com/inpsyde/multilingual-press/blob/master/inc/advanced-translator/Mlp_Advanced_Translator.php#L88

The problem is that one might disable the Advanced Translator in which case the notice shows.

**Comment by kraftner** [comment]
#148

**Comment by tfrommen** [comment]
Closed with #148.
