### ISSUE TITLE
save_context missing

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#150]
When using the advanced translator, `Mlp_Advanced_Translator_Data->save()` [is using](https://github.com/inpsyde/multilingual-press/blob/master/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L160) the [`Mlp_Translatable_Post_Data->update_remote_post_meta`](https://github.com/inpsyde/multilingual-press/blob/master/inc/post-translator/Mlp_Translatable_Post_Data.php#L296-L320) method. The problem is that this [is relying on the `$save-context` property](https://github.com/inpsyde/multilingual-press/blob/master/inc/post-translator/Mlp_Translatable_Post_Data.php#L313) which hasn't been set when using the Advanced Translator.
I think this is because the implementation of `update_remote_post_meta` was first only used in the same class and relied this property being initialized earlier on. But as the Advanced Translator bypasses a lot of the logic in `Mlp_Translatable_Post_Data` this doesn't work.

My first guess is that at least as an immediate fix one would need to copy the `save_context` over to the instance of `Mlp_Translatable_Post_Data` used in `Mlp_Advanced_Translator_Data`.

I am still not sure I've fully understood the scope, but I tried to summarize my findings so maybe you can jump in with a more thorough understanding of the full codebase.

**Comment by kraftner** [comment]
This is probably an issue that would vanish as soon as the split between Normal and Advanced Translator is removed as discussed in #125.

**Comment by kraftner** [comment]
I think this might be a regression introduced in 1968cde782cbd3346a9fa53f0157fc8bd0c4a310

**Comment by tfrommen** [comment]
Closed with e5414118d8e8d1f0d4f6a902c43f8a3c083ca591.
