### ISSUE TITLE
Changing a relation doesn't update the cache in Mlp_Content_Relations

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#151]
When a relation is changed, e.g. via [`Mlp_Content_Relations->insert_row`](https://github.com/inpsyde/multilingual-press/blob/ee75ce4a8fb4533b5ca3a6caa36fc416bfa697b3/inc/db/Mlp_Content_Relations.php#L248-L286) the internal cache in `Mlp_Content_Relations->checked` isn't updated.

Therefore when we have a request that changes the relations (e.g. adding a translation via the Translation Metabox) and [query for relations after the new relations are added we still get the old status before the change from `Mlp_Content_Relations->get_relations`](https://github.com/inpsyde/multilingual-press/blob/ee75ce4a8fb4533b5ca3a6caa36fc416bfa697b3/inc/db/Mlp_Content_Relations.php#L64-L66).

I noticed this via [`mlp_get_linked_elements`](https://github.com/inpsyde/multilingual-press/blob/ee75ce4a8fb4533b5ca3a6caa36fc416bfa697b3/inc/functions.php#L52-L63)

So I guess what we should do is invalidate the cache inside  `Mlp_Content_Relations->set_relation` and `Mlp_Content_Relations->delete_relation`.

Just collecting my findings and asking for opinions here before I try to come up with a PR.

**Comment by tfrommen** [comment]
Related #145.

**Comment by kraftner** [comment]
No idea how I missed that Issue. Sorry.

**Comment by tfrommen** [comment]
No problem. We're thankful for everything that helps (us) to make MultilingualPress yet a better piece of software. :)

As to trying to come up with a PR... We're already working on that, so in this case that's not necessary.

**Comment by kraftner** [comment]
Yep, saw that at the other issue. Looking forward to the fix.

Closing this as a duplicate.
