### ISSUE TITLE
Removing all terms via Advanced Translator is ignored

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#154]
If you remove all terms from a post using the Advanced Translator this change is ignored and everything just stays the way it was on the linked posts.

I think this is because [here](https://github.com/inpsyde/multilingual-press/blob/3e2d2ec89fa9abd9fad124933f07c4dc3929011c/inc/advanced-translator/Mlp_Advanced_Translator_Data.php#L170) you check for an empty `tax` key and abort tax syncing if empty. But when you remove all terms this being empty is actually a change to process.

**Comment by tfrommen** [comment]
Once again, good catch! This seems to have been broken forever.

**Comment by tfrommen** [comment]
Closed with 203609d7de46a703ceff1f4b3b3a003dec093ef2.
