### ISSUE TITLE
Content relations can't be deleted from the "other end"

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#156]
If you try to remove a content relation from the end it wasn't created originally this doesn't work.

The problem seems to be in [`Mlp_Content_Relations.php->delete_relation`](https://github.com/inpsyde/multilingual-press/blob/d478dc109995afb2f09d2ca9f23fa447163f2f54/inc/db/Mlp_Content_Relations.php#L194-L198). The where-clause doesn't consider this situation.

~~I'll continue playing around to see if coming from the wrong side also is an issue with other things like changing a relation.~~

I also wonder if this is an intended limitation or a known issue.

**Comment by tfrommen** [comment]
Closed as related to #143.

**Comment by kraftner** [comment]
I do not understand how that relates to #143.

#143 is about deleting the post. This is about deleting the relation as in "Change Relationship" => "Remove Relationship".

**Comment by tfrommen** [comment]
Ah, I see. Sorry for that. This will, however, be resolved as soon as the Content Relations refactor is done. Maybe we can provide a temporary fix for this sometime sooner, though.

**Comment by tfrommen** [comment]
Would you mind checking if the according branch works (for you)?

**Comment by kraftner** [comment]
Yes this fixes it for me.

Just out of curiosity - what is your reasoning to fix this like this and not inside `Mlp_Content_Relations.php->delete_relation`?
As the relations aren't directional (even though they are in the DB) I had assumed that should be standard behaviour that is always handled the same. Or is this something you do not want to touch now as it will be covered by the Content Relations refactor?

**Comment by tfrommen** [comment]
> Or is this something you do not want to touch now as it will be covered by the Content Relations refactor?
Yes.

**Comment by kraftner** [comment]
I see.

**Comment by tfrommen** [comment]
Closed with 9b54f88ff51e3d70cb943bfd15071b8b6e2156fc.
