### ISSUE TITLE
Linking to a post that is already linked to another post fails silently

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#157]
What I did:

> Site A
> - Post 1
>
> Site B
> - Post 1
> - Post 2
> 
> Link B1 -> A1
> Link B2 -> A1

This results in

1. B2 remains unlinked.
2. Each time you try this a duplication of the original link B1->A1 appears in the DB:

ml_source_blogid | ml_source_elementid | ml_blogid | ml_elementid | ml_type
---------------------- | --------------------------- | ------------- |------------------ | --------- |
2 | 1 | 1 | 1 | post
2 | 1 | 2 | 1 | post
2 | 1 | 1 | 1 | post
2 | 1 | 1 | 1 | post
2 | 1 | 1 | 1 | post
... | ... | ... | ... | ... 

I wonder what the solution for this would be?

-Just filter out posts that are already linked from the list of selectable posts.
-Remove the original link and replace it

I think the former makes more sense.

**Comment by kraftner** [comment]
If filtering connected posts out of the list one would need to [add this here](https://github.com/inpsyde/multilingual-press/blob/19324af1e6e7e22ae3d6392190a4e59c88bfe73a/inc/relationship-control/Mlp_Relationship_Control_Data.php#L86-L122).

Thinking about it you'd either replace the `get_posts` call with a custom query or do a separate query earlier for a list of IDs to exclude. Probably the latter.

**Comment by tfrommen** [comment]
Thanks for this.

Yes, it seems there is a UI flaw - and we simply shouldn't list remote posts that are already linked to some other post of the current blog.

Just a side note: We already have planned a complete refactor of the Content Relations for the next major release. So, duplicate entries won't be a problem in the future.

**Comment by kraftner** [comment]
On the sidenote: Let me know if I can be of any help there.

**Comment by tfrommen** [comment]
Closed with 00ae884f509f2f754ca51da66e5680578cfa5ee2.
