### ISSUE TITLE
Add the limitations to the table prefix to README

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/multilingual-press#158]
With 2.2.0, the validation of table names, including validation of the table prefix merged into the public version which triggered [this issue](https://wordpress.org/support/topic/update-to-220-on-wp-43-broke-site-invalid-table-name). 

The scheme of the required prefix should be documented within the readme files.

**Comment by bueltge** [comment]
A topic for the FAQ sector inside the readme

**Comment by toscho** [comment]
We had _one_ question. The FAQ and the readme in general should be limited to _common_ questions. Write a post about that on the dev blog, add the link to the error message. That should cover 99% of all cases.

**Comment by dnaber-de** [comment]
I would add a hint inside the requirements section of the readme. The thing is, this can (and probably should) be read _before_ you install the plugin. +1 for the blog post.

**Comment by toscho** [comment]
This is way too technical for a readme and not an issue for most users. That file should be *read*, so we have to keep it as short and understandable as possible. If you add a graceful error handling, no harm will be done when someone hits this problem later.

**Comment by tfrommen** [comment]
We decided to not be more restrictive than WP core, so there is no need for this anymore.
