### ISSUE TITLE
Graceful handling for invalid prefix name

### ISSUE THREAD

**Issue by dnaber-de** [inpsyde/multilingual-press#159]
As mentioned in #158, the validation of the table prefix of any installation ends up with (at worst) a fatal error which is the worst situation when someone activates a plugin. 

I suggest to perform the check early before init the plugin logic and print an admin notice if the validation fails. The init process should then just get stopped.

**Comment by tfrommen** [comment]
We decided to not be more restrictive than WP core, so there is no need for this anymore.
