### ISSUE TITLE
Term Relations can't be changed from the "other end"

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#160]
Sites A and B

Tags A1, A2, B2

Link A1 -> B1 while in A
Change B1 -> A2 is ignored silently

This is especially bad as in contrast to the post edit screen you get redirected to the term list page which means you won't even see that the change is ignored.

For some reason in[`Mlp_Term_Connector->update_terms`](https://github.com/inpsyde/multilingual-press/blob/19324af1e6e7e22ae3d6392190a4e59c88bfe73a/inc/term-translator/Mlp_Term_Connector.php#L269-L274) the target term is changed. I don't really understand the logic there. Is this trying the inverse the relation?

**Comment by tfrommen** [comment]
Yes, this is currently not possible. This will, also, be fixed in the course of the Content Relations refactor, and unfortunately not before that.

**Comment by kraftner** [comment]
Could we at least disable the select box on the "other end" until then?

Or is the Content Relations refactor already happening really soon?

**Comment by tfrommen** [comment]
Closed with 88686e946174dee8b17104c20ad4ea1e49f31bcb.
