### ISSUE TITLE
This plugin must be activated for the network. Also on network plugin page

### ISSUE THREAD

**Issue by jackblackCH** [inpsyde/multilingual-press#162]
I am on the network page. All the time the same error on activating the plugin:

> This plugin must be activated for the network. Please use the network plugin administration.

Wordpress: 4.3 (Tried also with 4.2)
Deactivated all other plugins

Do I miss special settings?

**Comment by jackblackCH** [comment]
I found out: we have symlinked the theme and you are doing a plugin file check of paths in check_activation()

if you don't convert the $plugin_file path to a realpath (with realpath())
there is a small difference between the paths you compare and the important line will not return true

fixed with: 
Mlp_Requirements_Check.php, line 176
$plugin_file = $this->normalize_path( realpath($plugin) );

**Comment by tfrommen** [comment]
Thank you for the issue - and the fix as well! :)

Would you mind checking if [the according branch](https://github.com/inpsyde/multilingual-press/tree/issue/162_check_activation) works for you?

**Comment by tfrommen** [comment]
Closed with 6709e9fdded3089dab30af8003ba1e92461e041f.
