### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingual-press#163]
- [x] Create screenshots of all fitting
  - [x] network admin pages/modules
    - [x] `/wp-admin/network/sites.php` (new columns)
    - [x] `/wp-admin/network/site-info.php?id=2` (edit site, MLP Tab)
    - [x] `/wp-admin/network/site-new.php` (example data of a new site)
    - [x] `/wp-admin/network/settings.php?page=mlp` (all checkboxes ticked, at least one active CPT)
    - [x] `/wp-admin/network/settings.php?page=language-manager`
  - [x] admin pages/modules
    - [x] `/wp-admin/` (dashboard widget)
    - [x] `/wp-admin/post-new.php` (_Translation_ meta boxes and additions to the _Publish_ meta box)
    - [x] `/wp-admin/edit-tags.php?taxonomy=category`
    - [x] `/wp-admin/edit-tags.php?action=edit&taxonomy=category&tag_ID=1&post_type=post` (example term)
    - [x] `/wp-admin/profile.php` (_Your preferred backend language_)
    - [x] `/wp-admin/widgets.php` (_Language Switcher_ widget)
  - [x] front-end modules
    - [x] Quicklinks
    - [x] _Language Switcher_ widget
- [x] Integrate Screenshots into
  - [x] `readme.md` (for GitHub)
  - [x] `readme.txt` (for wordpress.org)

**Comment by bueltge** [comment]
Now live on https://wordpress.org/plugins/multilingual-press/screenshots/
Upload currently only on svn - http://plugins.svn.wordpress.org/multilingual-press/assets/

**Comment by bueltge** [comment]
* network settings
* frontend view
* table of sites with new columns

**Comment by bueltge** [comment]
[ ] Update `readme.md` after new git structure necessary
[ ] Upload screenshots from svn - assets

**Comment by tfrommen** [comment]
As soon as the `issue/164_file_structure` branch is merged into master, this can be closed as well.
