### ISSUE TITLE
No content showing on translated pages

### ISSUE THREAD

**Issue by mattevolve** [inpsyde/multilingual-press#165]
I've followed the install tutorial, setup 2 sites within my network (/ and /nl/), but when I view my translation pages I get a white page with no HTML content. It seems like it cannot find what theme template file to use? Where have I gone wrong?

**Comment by tfrommen** [comment]
Hi there,

first of all, sorry, this issue must have sneaked past us&mdash;we simply didn't notice it until now.

Then second, the Issues section here is (primarily) intended for bug reports, feature requests, enhancements and the like, and not for support (even though technical).

Would you mind posting this again (with more details) on the [wordpress.org support forum](https://wordpress.org/support/plugin/multilingual-press)? Thanks.

And BTW, a white screen usually indicates a PHP Fatal Error before there was something output.
