### ISSUE TITLE
Can't get language code

### ISSUE THREAD

**Issue by arifamrullah** [inpsyde/multilingual-press#167]
I need a language code for my web with my custom theme.
I've called the language with this on my function : <a href="http://make.marketpress.com/multilingualpress/2015/02/how-to-get-translations-programmatically/">How to get translation programmatically</a>
But the result is null, and when I print_r the ($translation), the result is Array().
I've set my language site like <a href="http://postimg.org/image/liszohb0h/">this</a>.
And I have no idea how to call its language code. Please help.

Regards, Arif Amrullah from Indonesia.

https://wordpress.org/plugins/multilingual-press/

Repost from wordpress : https://wordpress.org/support/topic/cant-get-language-code

**Comment by dnaber-de** [comment]
I wrote an answer at the WordPress support forum. Please use the WordPress support forum as the preferred contact point for support questions. This issue tracker here should be used for bug reports. 

Cross-posts are not necessary we're keeping an eye on both platforms.
