### ISSUE TITLE
WooCommerce Orders (shop_order) all have 0 products in new sites

### ISSUE THREAD

**Issue by fabianhenzler** [inpsyde/multilingual-press#172]
When creating a new localized site with the WooCommerce plugin activated on the main site, all orders just have 0 products attached in the new sites.
https://db.tt/7A2MvcmA
![scr_2015-09-16_07-20-22_pm](https://cloud.githubusercontent.com/assets/1168345/9912626/e35ee5dc-5ca8-11e5-97c5-b8dafe1374de.png)

Can I easily add the `shop_order` custom post type?

**Comment by fabianhenzler** [comment]
can I easily add the shop_order custom post type?

**Comment by bueltge** [comment]
Do you have WooCommerce active as single activation, in each site of the network there will use Woo?
If you will sync the data of woo, then it is necessary, that you create a synchronization, is not a part of MLP, our plugin. But we have a add on, currently not released, but stable Beta. Maybe you will test this?

But if you will only add the CPT, than see in the settings of MLP, there have a area for CPTs. Here is the activation necessary.
![multilingualpress network admin wp beta dev sites wordpress](https://cloud.githubusercontent.com/assets/133425/9914920/847136b8-5cb4-11e5-8fa5-fe3d6ff9e4ff.png)

**Comment by fabianhenzler** [comment]
Hi @bueltge 
yes, both are activated in the Network Settings and WooCommerce is activated on each Site. Otherwise I wouldn't be able to see the Orders in those Sites.

I tried MultiWoo, but probably not the latest Version. Is there a way to give me access to the repo so I'm sure I'm on the latest version?
But I guess MultiWoo doesn't sync shop_orders and it should be working with MLP, right?

**Comment by fabianhenzler** [comment]
Here is a little screencast https://www.dropbox.com/s/8vegj1spzfdn4gx/mlp-woo.gif?dl=0

**Comment by bueltge** [comment]
Hi @fabianhenzler 
Sorry, we have only a static image, can you check. Thx!
Also, please write me a short mail to `f.bueltge AT inpsyde DOT com` and I send you the current version of MultiWoo.

**Comment by fabianhenzler** [comment]
just download the animated gif (20MB) - email is out

**Comment by fabianhenzler** [comment]
http://youtu.be/qG8zOPFBWi4

**Comment by bueltge** [comment]
switch to mail support.
