### ISSUE TITLE
Duplicate site feature doesn't link the translations

### ISSUE THREAD

**Issue by orbitaloop** [inpsyde/multilingual-press#173]
I created a new translation from an existing site (with more than 200 pages) using the Duplicate Site feature of MultilingualPress. I was expecting that all the cloned posts would have been linked to the according original language's post, but it looks like they are not.

I found this old ticket: https://github.com/inpsyde/multilingual-press/issues/5

In the DB, it seems that the translations are linked in the `wp_multilingual_linked` table, but in the website, I don't see any links to the translation and the translation editor is empty:
![Screenshot](https://www.dropbox.com/s/wu39mh1vpe6uq6e/Screenshot%202015-09-16%2019.59.07.png?dl=0)

And I don't see any "Quick link" saying read this page in French...

Am I missing something?

**Comment by bueltge** [comment]
Short from my mobile. All posts are published in his status? On default we create a draft after duplicate.

**Comment by orbitaloop** [comment]
Thank you very much for your answer. The website have Pages (not post), and all the duplicated pages are in the Status: Published. But the pages are not linked to the original translation.
Should I create a new post in the Wordpress support forum?

**Comment by bueltge** [comment]
Yes, please. A transfer to wp.org Forum is also helpful for other users.

**Comment by orbitaloop** [comment]
But which forum category? Plugins and Hacks? Because it concerns Multilingual-Press only. Also, if I decide to go with Multilingual-Press, I will be willing to pay for the support. But for now, I am not sure yet if it's good for our needs.

**Comment by bueltge** [comment]
Do you shouldl use this free forum for now - https://wordpress.org/support/plugin/multilingual-press

**Comment by orbitaloop** [comment]
Thanks, I created the post:
https://wordpress.org/support/topic/duplicate-site-feature-doesnt-link-the-translations?replies=1#post-7438113

**Comment by bueltge** [comment]
Thanks!
We will check this. Normally in our last tests works this, creating of relationship between post/post. Maybe we have difference on `page`. From here I will switch the conversation in the support forum.

**Comment by orbitaloop** [comment]
Hi, please, don't forget my post : https://wordpress.org/support/topic/duplicate-site-feature-doesnt-link-the-translations?replies=1
Thanks in advance

**Comment by bueltge** [comment]
It is not forgotten, but not easy to readjust in our landscape.

**Comment by orbitaloop** [comment]
I am willing to pay for support...
