### ISSUE TITLE
?noredirect parameter is missing when redirect feature is active

### ISSUE THREAD

**Issue by nullbytes** [inpsyde/multilingual-press#174]
In version 2.1.2 we added the `?noredirect` parameter to every link on quicklinks and the language widget. In 2.2.3 the parameter is missing, and if the redirect feature is active, you get redirected to the page you was just leaving.

Example: 
0. Location: /de/unternehmen/
1. Click on link to: /en/company/
2. Redirect to: /de/unternehmen/?noredirect=de_DE

More information: https://wordpress.org/support/topic/back-redirection-after-switching-the-language?replies=4

**Comment by dboune** [comment]
I am seeing odd behavior here as well. I have a live example, but would need to email someone directly about it. If interested please contact me via email with the user of dboune, and the domain of gmail.com. I will send you the domain, along with my own repro instructions. Three linked languages, with redirect.
