### ISSUE TITLE
Alternative language slugs not shown properly

### ISSUE THREAD

**Issue by daslicht** [inpsyde/multilingual-press#175]
Hi,
I have setup a multisite with 2 languages eg:

Mydomain.tld
Mydomain.tld/de

But when I call the translation for 'de' its slug is not shown and I get ugly get parameters shown instead.

What am I missing please ?

**Comment by bueltge** [comment]
@daslicht Please use the WordPress support forum as the preferred contact point for support questions.

Please write moire about the configuration. Do you have set the relation between this two sites in the network? Permalinks are active, also refresh after create a site. The relationship between posts are set?

**Comment by daslicht** [comment]
Do you have set the relation between this two sites in the network?
yes

Permalinks are active
yes

The relationship between posts are set?
yes
 I keep trying

Thanks
