### ISSUE TITLE
Link »Update« missing on Plugins-page.

### ISSUE THREAD

**Issue by te-online** [inpsyde/multilingual-press#176]
See screenshot: The link to directly update the plugin with the new ajax-update-method is missing.
This is WordPress version 4.3.1
Plugin version 2.1.2 Pro
Of course the key is actually provided but not on the screenshot.

<img width="1492" alt="bildschirmfoto 2015-09-20 um 19 57 19" src="https://cloud.githubusercontent.com/assets/4127167/9982164/9ce0bc70-5fd2-11e5-82df-6a6f8e7f8001.png">

Maybe this was solved by the update? If so, just ignore me :wink: 

And a thing of personal taste: The **green bar** is really distracting when managing the plugins page. It calls a lot for attention. Maybe there could be a more unobtrusive solution in the future :relaxed:

**Comment by te-online** [comment]
Oh, now it somehow appeared in a different backend – but blue instead of red... I don't know what's going on there.

<img width="1476" alt="bildschirmfoto 2015-09-20 um 20 10 39" src="https://cloud.githubusercontent.com/assets/4127167/9982199/ba07fc90-5fd3-11e5-8401-2c11ce15a5f5.png">

**Comment by te-online** [comment]
Okay, just read this one https://marketpress.de/2015/multilingualpress-mehrsprachiges-wordpress/

Forget what I said... :smile:

**Comment by bueltge** [comment]
Alternative also in English language - https://marketpress.com/2015/multilingual-wordpress-free/
