### ISSUE TITLE
Translation Widget in Dashboard links back to source post

### ISSUE THREAD

**Issue by konus1** [inpsyde/multilingual-press#180]
I would like to give translators as less rights a necessary. Right now, a translator needs to have editor role in the translation site **and** in the original site.

On the translation site, the translator finds new blog entries in his dashboard, but the link leeds back to the original site. For me, this feels like a bug. I think it would be much better, if he can edit the draft in the translation site also.

**Comment by tfrommen** [comment]
Will be handled in #190.
