### ISSUE TITLE
Documentation deviates from implementation at Mlp_Language->get_name

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#183]
There it says
> 'lang': Alias for 'language_short'.

But as `$names['lang']` exists [this](https://github.com/inpsyde/multilingual-press/blob/172b6d4cfd24ba682debdaaaac590efe1f35471a/src/inc/types/Mlp_Language.php#L74-L76) is true and we never get [here](https://github.com/inpsyde/multilingual-press/blob/172b6d4cfd24ba682debdaaaac590efe1f35471a/src/inc/types/Mlp_Language.php#L82-L84).

I don't know if the implementation is wrong or the documentation. Just wanted to report this anyway.

**Comment by tfrommen** [comment]
Nice catch. :)

The `lang` entry shouldn't even be there at all. It's just that the site option in which we store the (basic) language information about each site serves as a starting point for generating the complete languages data array. We just didn't unset the `lang` entry.
