### ISSUE TITLE
Site Duplication creates different links than manual linking

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#185]
I have a CPT 'client' that when duplicated on site duplication has links with `ml_type` of `client` in the `wp_multilingual_linked` table, but that is then ignored in the UI. When re-creating the links they are created with `ml_type` of `post` which also makes them show up in the UI.

I had a quick look at the code and it seems that on duplicating the post type [is taken from the `*_posts` table](https://github.com/inpsyde/multilingual-press/blob/ae717cca761c18b0e97853dcc37ab8f93f8b938a/src/inc/copy-site/Mlp_Duplicate_Blogs.php#L286-L296) while later [everything uses the default `post`](https://github.com/inpsyde/multilingual-press/blob/ae717cca761c18b0e97853dcc37ab8f93f8b938a/src/inc/post-translator/Mlp_Translatable_Post_Data.php#L81) if I got that right.

Maybe this is something that will be addressed with #171 Is the corresponding branch stable enough to be worth testing already? (Although looking at the lines referenced above I do not see any change)

Or did I get something completely wrong here?

**Comment by tfrommen** [comment]
This is definitely a bug in the duplicate blog method you referenced. We used to store the post type slug, but then changed to generic `post` for a number of reasons. We simply overlooked that we're still using the actual `post_type` field of the posts in that method.

As to #171, the according branch is still work-in-progress. While there are open issues with post translation, the translation of terms should work as expected, though.
If you'd like to, you can go and test it out. In a *testing* environment, please. :)
As you can see in the checkbox list, there is currently no migration. You just have to start with no relationships.
No promise included, but I have January 2016 reserved for #171.

**Comment by kraftner** [comment]
Thanks for the fix. Just one more question:

When you have created a link manually after the site duplication you might end up with multiple/duplicate entries in the link table. Off the top of my head I am not sure - should this be handled in the plugin update routine or is this handled somewhere else anyway?

**Comment by tfrommen** [comment]
[This change](https://github.com/inpsyde/multilingual-press/blob/c37fc75e8b73083f283a74c18e5883a9ada2a49f/src/inc/installation/Mlp_Update_Plugin_Data.php#L106) that I made yesterday updates table entries with a custom post type slug as `ml_type` value. After this, you have two (or maybe even more) entries that are the same, except for the `ml_id` field. This is not what we want, yes, but it doesn't hurt either, because the (correct) access to the database happens via [`Mlp_Content_Relations::get_relations`](https://github.com/inpsyde/multilingual-press/blob/c37fc75e8b73083f283a74c18e5883a9ada2a49f/src/inc/db/Mlp_Content_Relations.php#L166-L168), where we filter out duplicate entries.

**Comment by kraftner** [comment]
Cool, that is what I meant by "is this handled somewhere else anyway".

**Comment by kraftner** [comment]
But the more I think about it - wouldn't it be better to just delete those entries? I mean they didn't have any effect up until now and where just lying around in the DB. Isn't it really unexpected to "revive" them, possibly a long time after the initial duplication?

**Comment by tfrommen** [comment]
Yes, of course, this will happen. In the course of the content relations refactor, that is. In the according branch, there is already a [method for cleaning up *invalid* entries](https://github.com/inpsyde/multilingual-press/blob/7bbdbeb9a9fcc8ab17d8a985e89394880da336c5/src/inc/installation/Mlp_Update_Plugin_Data.php#L188). Removing duplicates (after having adapted the `ml_type` values) will also happen, yes.

**Comment by kraftner** [comment]
[OT] Okay, awesome. Have a nice Christmas then to power-up for an exiting January! [/OT]

**Comment by tfrommen** [comment]
Thanks. You too.
:christmas_tree: :muscle: :smile:
