### ISSUE TITLE
Mlp_Advanced_Translator_View post_name non-ascii characters support

### ISSUE THREAD

**Issue by luisarn** [inpsyde/multilingual-press#186]
Wordpress stores the url encoded post_name on DB if the post_name has non-ascii characters.

Mlp_Advanced_Translator_View show_name function lacks the urldecode on the $value so it will display the encoded characters on the input field.

I added this line: 
$value = urldecode($value);   
right after the line 104 of Mlp_Advanced_Translator_View.php:
$value = esc_attr( $value );
to solve the issue.

Maybe you can add it to the master branch in the next update?

Thanks!
Luis

**Comment by tfrommen** [comment]
Hey Luis,

I changed the order (escaping comes last), but thanks for the issue (and fix as well). Much appreciated. :)

Thorsten
