### ISSUE TITLE
Relationship control search

### ISSUE THREAD

**Issue by luisarn** [inpsyde/multilingual-press#193]
Hi!

The backend.js used on the relationship control search only triggers the search when the user input 3 or more characters.

However in Chinese, a lot of titles only contains 2 characters, making the user unable to search for the corresponding post.

Maybe you could trigger the search when the 2nd character is typed?

Thanks~!
Best regards,
Luis

**Comment by tfrommen** [comment]
Hi Luis,

well, that's interesting. :)

I understand the problem here, however, 3 is a pretty good threshold for _a huge part of languages_, so I would rather offer a filter to adapt the value instead of loweing it to 3 in general. Are you okay with this?

**Comment by luisarn** [comment]
Hi Thorsten, I think is fine if it's configurable! Probably only the Chinese language has this issue because each character has a meaning.

Thanks!
Luis
