### ISSUE TITLE
wp_nav_menu Languages

### ISSUE THREAD

**Issue by luisarn** [inpsyde/multilingual-press#194]
I'm currently using the wp_nav_menu to render the language options of my network.

But for custom post type with a custom post base for each language, the menu is not rendering correctly.

Let's say if I have site A in English:
http://www.example.com/en/browse/projects/project-2016/introduction
where "browse/projects/" is the custom post base

And site B in Portuguese:
http://www.example.com/pt/navegacao/projectos/projecto-2016/introducao
where "navegacao/projectos/" is the custom post base

When I navigate trough site A (English), the language menu will render the following urls:
English - http://www.example.com/en/browse/projects/project-2016/introduction
Portuguese - http://www.example.com/pt/browse/projects/projecto-2016/introducao

Or if I navigate though site B (Portuguese), the language menu will render the following urls:
English - http://www.example.com/en/navegacao/projectos/project-2016/introduction
Portuguese - http://www.example.com/pt/navegacao/projectos/projecto-2016/introducao

After digging into the MLP code I figured out it's calling the get_permalink function of Wordpress in order to get the urls and as far as I know the get_permalink will look into the rewrite rules structure from the site to return the permalink, however site A (English) will never have the rewrite rules of site B (Portuguese) or vice-versa.

So far if I disable the pretty permalink function the urls work correctly. 

I would like to ask the authors if you have any solution for this custom post base issue or is there any way I could set only the language menu to don't use the pretty permalink?

For ex. if I access via post ID it works correctly:  http://www.example.com/en/?p=123

Thanks!
Luis

**Comment by tfrommen** [comment]
This is related to #192. I'm closing this as a duplicated (which it is not completely, but it depends on incorrect _custom rewrite structures_).
