### ISSUE TITLE
Advanced translator copy post button doesn't copy the post full name

### ISSUE THREAD

**Issue by luisarn** [inpsyde/multilingual-press#195]
Hi, 

The Advanced Translator copy post button doesn't copy the post full name if the post title is too long.
Wordpress automatically shortens the generated post name, putting dots in the middle if the title is longer than a certain number of characters.

Changing the admin.js / admin.min.js line 55, from:

postSlug = $( '#editable-post-name' ).html();

to:

postSlug = $( '#editable-post-name-full' ).html();

should solve this issue.

Best regards,
Luis

**Comment by tfrommen** [comment]
Hi Luis,

thanks for the issue (and the fix).
I just adapted this in the `master`, and I also fixed an unrelated bug with the post slug.

Thanks again,
Thorsten
