### ISSUE TITLE
Programatically link post translations

### ISSUE THREAD

**Issue by hatsumatsu** [inpsyde/multilingual-press#197]
Hi there!

Does the plugin currently have an API method to programmatically link existing posts as translations from different sites within a network?

I'm currently writing a plugin that cross uploads attachments to other sites and I would like to mark these `attachment` posts as translations to maintain the relationship between them (f.e. to later track and sync their deletion).

I imagine handing the function an array of `site_id -> post_id` pairs...

Thx!

**Comment by dnaber-de** [comment]
Hi there,

yes, the `Mlp_Content_Relations_Interface` is exactly for this purpose:

```
Mlp_Content_Relations_Interface::set_relation(
    int $source_site_id,
    int $target_site_id,
    int $source_content_id,
    int $target_content_id,
  [ string $type = 'post' ]
```

To get an instance of an implementation of this interface you can use the action `inpsyde_mlp_loaded`:

```php
add_action( 
    'inpsyde_mlp_loaded', 
    function ( Inpsyde_Property_List_Interface $data ) {
        /* @var Mlp_Content_Relations_Interface $content_relation_api */
        $content_relation_api = $data->get( 'content_relations' );
}
```

By default, this returns you a `Mlp_Content_Relation` object.

**Comment by hatsumatsu** [comment]
Thanks @dnaber-de, looks exactly like what I need. But I'm not sure if I understand the nature of the API being implemented as an action correctly. I added 

```
add_action( 'inpsyde_mlp_loaded', function( $data ) {
    /* log if the action is fired... */
} );
```

in a function called by the `add_attachment` filter but the `inpsyde_mlp_loaded` action does not fire.
I guess your action is not yet available at the time `add_attachment` is called? Do you have any hints on how to use it under these conditions?

Thx!

**Comment by tfrommen** [comment]
It's the other way around: you're too late with `add_attachment`. You have to cache the property list ( i.e., `$data` in the above code), and then later on fetch the Content Relations object, and do what you want to do.

**Comment by hatsumatsu** [comment]
thanks for pointing me in the right direction, that works!

**Comment by tfrommen** [comment]
Glad it works. :)
