### ISSUE TITLE
Programatically get related taxonomy terms

### ISSUE THREAD

**Issue by hatsumatsu** [inpsyde/multilingual-press#199]
Hi! How can I retrieve all the linked/translated terms of a given taxonomy term within the network?

**Comment by Biont** [comment]
Hello!

There's a method for that:

```php
Mlp_Content_Relations_Interface::get_relations(
    int $source_site_id,
    int $source_content_id,
  [ string $type = 'post' ]
)
```

Note the optional `$type` parameter. You will want to pass `term` into the method to receive linked terms.

Grab the Mlp_Content_Relations object as described in #197:
```php
add_action( 
    'inpsyde_mlp_loaded', 
    function ( Inpsyde_Property_List_Interface $data ) {
        /* @var Mlp_Content_Relations_Interface $content_relations */
        $content_relations = $data->get( 'content_relations' );
}
```
Then, use `$content_relations->get_relations( $source_site_id, $source_content_id, 'term' )` to fetch the linked terms. Hope this helps

**Comment by hatsumatsu** [comment]
Works perfectly! Thanks, especially for the great support around here!
