### ISSUE TITLE
Module Configuration not working without SCRIPT_DEBUG

### ISSUE THREAD

**Issue by kraftner** [inpsyde/multilingual-press#205]
#### Version Information
* WordPress: 4.4.3
* MultilingualPress: 2.4.0

#### Steps to Reproduce
1. Open Apperance/Menus
2. Click "Add to Menu"
3. Nothing happens

#### What I Expected

a language menu item being added.

#### What Happened Instead

Nothing

----------------

When I `define('SCRIPT_DEBUG', true);` it works. Also Firefox Developer Toolbar confirms there are no listeners attached without `SCRIPT_DEBUG`. Unfortunately debugging in the minified file (without source maps) is hard so I have no clue where the issue lies for now.

**Comment by kraftner** [comment]
Okay there seems to be something wrong with the compiled version of [`functions.js`](https://github.com/inpsyde/multilingual-press/blob/0705b0f279888c6f6e04030200ca2655fb1b50ca/resources/js/admin/core/functions.js)

I think the issue is that building the name of the config variable from the module name doesn't work as it may be changed during minification.

**Comment by kraftner** [comment]
Okay the issue seems to be bigger than I thought. This doesn't only affect the NavMenu module but any module that has configuration settings.

Here is another example: When changing a relation and saving the post without first saving the relation change there is an error (`Uncaught TypeError: Cannot read property 'unsavedRelationships' of undefined`) and the modal warning about lost data doesn't show up.

**Comment by kraftner** [comment]
Okay I think I've got it. [function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions) is changed on minification. This approach feels fragile in any case.
 [This](https://github.com/inpsyde/multilingual-press/blob/0705b0f279888c6f6e04030200ca2655fb1b50ca/resources/js/admin/core/functions.js#L9) doesn't behave as expected when minified.

**Comment by tfrommen** [comment]
@kraftner thanks for the issue as well as your investigative work.

I already fixed this, so you may expect a patch release really soon.

**Comment by kraftner** [comment]
Cool. Just tested on master, all working now. Thanks for the extremely fast response!
