### ISSUE TITLE
All checkboxes ticked after saving Language Switcher widget settings

### ISSUE THREAD

**Issue by tfrommen** [inpsyde/multilingual-press#209]
When saving changes to a Language Switcher widget, the form markup included in the according AJAX request response shows all checkboxes ticked, and not only the ones that have actually been checked before. Fortunately, the settings saved are actually the correct ones, though.

**Comment by 2ndkauboy** [comment]
Somehow the latest update broke the language switcher. It looks like the CSS is no longer loaded on the frontend. You can see the issue on my page: https://kau-boys.de/

**Comment by tfrommen** [comment]
@2ndkauboy do you have version **2.4.2** installed? This should have been fixed already...?

**Comment by 2ndkauboy** [comment]
Yes, I am using version 2.4.2 of the plugin. Any idea why the file might not be loading?
