### ISSUE TITLE
Mlp_Term_Fields' not found

### ISSUE THREAD

**Issue by kochhase** [inpsyde/multilingual-press#211]
#### Version Information
* WordPress: 4.4.2
* MultilingualPress: 2.4.2 (master) /the 2.4.1 before

#### Steps to Reproduce
1. 
2. 
3. 

#### What Happened Instead
Class 'Mlp_Term_Fields' not found in /var/www/web529/html/334_wordpress/wp-content/plugins/multilingual-press/src/inc/term-translator/Mlp_Term_Translation_Controller.php on line 73

**Comment by tfrommen** [comment]
Hi there,

thanks for the issue, however, this is not enough information.

* On what page are you, and what are you trying to do?
* Can you confirm that you physically have the file `/var/www/web529/html/334_wordpress/wp-content/plugins/multilingual-press/src/inc/term-translator/Mlp_Term_Fields.php`?
* If you don't have the file, how did you *get* MultilingualPress? Clone the repo? Download the ZIP? Something else?

Kind regards,
Thorsten

**Comment by tfrommen** [comment]
@kochhase any news on this?

**Comment by tfrommen** [comment]
No feedback here. I'm closing this, for now.
