### ISSUE TITLE
The language switcher does not show the link to translation for the blog page

### ISSUE THREAD

**Issue by grappler** [inpsyde/multilingual-press#225]
#### Version Information
* WordPress: 4.5.3
* MultilingualPress: 3.0.0 beta

#### Steps to Reproduce
1. Have a site with the blog posts as the front page
2. Add a language switcher widget 

#### What I Expected
To see a link to the translation

#### What Happened Instead
There was no link to the translation

**Comment by tfrommen** [comment]
Sorry, this is lacking information.

From the provided information I don't know how many sites you have, if the sites are related, if they all have a MultilingualPress language assigned, how you configure the Language Switcher widget, ...

**Comment by grappler** [comment]
We have only connected sites. One site is English and the other in German and they have a MultilingualPress language assigned to them. I tried changing the Language Widget settings but it did not help. We have the same problem when using `mlp_show_linked_elements()`

**Comment by tfrommen** [comment]
Did you check the _Show links for translated content only_ checkbox in the widget settings? This should work.

When using the `mlp_show_linked_elements()` function, pass `[ 'strict' => false ]` as (part of the) argument(s). This is set by default, though.

**Comment by grappler** [comment]
Even unchecked it does not work. The language switcher works fine on the normal pages just not on the front blog page.

**Comment by toscho** [comment]
Is the page for the front page marked as translation for another page on other sites?

**Comment by grappler** [comment]
The front page is the latest posts so there is no page to edit or connect.

**Comment by tfrommen** [comment]
I understand you are a developer, right?
Can you _debug_ what [this line](https://github.com/inpsyde/multilingual-press/blob/b8faca5c58eb2136d851e3f9e00d7e0ed0e0dd37/src/inc/language-api/Mlp_Language_Api.php#L330) gives?
Can you show us the contents of `$arr` and `$arguments`?

**Comment by grappler** [comment]
Here are the results from the home page:

`$arr`
<details><pre>
array(5) {
  ["remote_title"]=&gt;
  string(0) ""
  ["source_site_id"]=&gt;
  int(1)
  ["target_site_id"]=&gt;
  string(1) "2"
  ["target_content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
}
array(5) {
  ["remote_title"]=&gt;
  string(0) ""
  ["source_site_id"]=&gt;
  int(1)
  ["target_site_id"]=&gt;
  string(1) "3"
  ["target_content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
}
array(5) {
  ["remote_title"]=&gt;
  string(0) ""
  ["source_site_id"]=&gt;
  int(1)
  ["target_site_id"]=&gt;
  string(1) "6"
  ["target_content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
}
array(5) {
  ["remote_title"]=&gt;
  string(0) ""
  ["source_site_id"]=&gt;
  int(1)
  ["target_site_id"]=&gt;
  int(1)
  ["target_content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
}
</pre></details>

`$arguments`
<details><pre>array(8) {
  ["site_id"]=&gt;
  int(1)
  ["content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
  ["strict"]=&gt;
  bool(true)
  ["search_term"]=&gt;
  string(0) ""
  ["post_type"]=&gt;
  string(0) ""
  ["include_base"]=&gt;
  bool(true)
  ["suppress_filters"]=&gt;
  bool(true)
}
array(8) {
  ["site_id"]=&gt;
  int(1)
  ["content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
  ["strict"]=&gt;
  bool(true)
  ["search_term"]=&gt;
  string(0) ""
  ["post_type"]=&gt;
  string(0) ""
  ["include_base"]=&gt;
  bool(true)
  ["suppress_filters"]=&gt;
  bool(true)
}
array(8) {
  ["site_id"]=&gt;
  int(1)
  ["content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
  ["strict"]=&gt;
  bool(true)
  ["search_term"]=&gt;
  string(0) ""
  ["post_type"]=&gt;
  string(0) ""
  ["include_base"]=&gt;
  bool(true)
  ["suppress_filters"]=&gt;
  bool(true)
}
array(8) {
  ["site_id"]=&gt;
  int(1)
  ["content_id"]=&gt;
  int(0)
  ["type"]=&gt;
  string(10) "front_page"
  ["strict"]=&gt;
  bool(true)
  ["search_term"]=&gt;
  string(0) ""
  ["post_type"]=&gt;
  string(0) ""
  ["include_base"]=&gt;
  bool(true)
  ["suppress_filters"]=&gt;
  bool(true)
}
</pre></details>

**Comment by tfrommen** [comment]
Thanks.
However, this is most likely the wrong data. Since the `suppress_filters` argument is set to true, this is when the **unfiltered** translations are being fetched to be used for the alternate language links and headers.

In case this is the complete output, the code from my link isn't reached at all for widget display.
Do you have any object-caching enabled?

Can you check how often the `Mlp_Language_Api::get_translations()` method is called?

**Comment by grappler** [comment]
The output from `Mlp_Language_Api::get_translations()` is:

<details><pre>
array(4) {
  [2]=&gt;
  object(Inpsyde\MultilingualPress\Common\Type\FilterableTranslation)#6332 (9) {
    ["icon_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6333 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(95) "http://stories-dev.required.ch/wp-content/plugins/multilingual-press/assets/images/flags/fr.gif"
    }
    ["language":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage)#6331 (3) {
      ["is_rtl":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      bool(true)
      ["names":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      array(6) {
        ["english_name"]=&gt;
        string(15) "French (France)"
        ["native_name"]=&gt;
        string(2) "FR"
        ["custom_name"]=&gt;
        string(0) ""
        ["text"]=&gt;
        string(2) "FR"
        ["http_name"]=&gt;
        string(5) "fr-FR"
        ["wp_locale"]=&gt;
        string(5) "fr_FR"
      }
      ["priority":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      int(6)
    }
    ["remote_title":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(0) ""
    ["remote_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6330 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(0) ""
    }
    ["source_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(1)
    ["suppress_filters":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    bool(true)
    ["target_content_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(0)
    ["target_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(2)
    ["type":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(10) "front_page"
  }
  [3]=&gt;
  object(Inpsyde\MultilingualPress\Common\Type\FilterableTranslation)#6328 (9) {
    ["icon_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6329 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(95) "http://stories-dev.required.ch/wp-content/plugins/multilingual-press/assets/images/flags/it.gif"
    }
    ["language":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage)#6327 (3) {
      ["is_rtl":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      bool(true)
      ["names":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      array(6) {
        ["english_name"]=&gt;
        string(7) "Italian"
        ["native_name"]=&gt;
        string(2) "IT"
        ["custom_name"]=&gt;
        string(0) ""
        ["text"]=&gt;
        string(2) "IT"
        ["http_name"]=&gt;
        string(5) "it-IT"
        ["wp_locale"]=&gt;
        string(5) "it_IT"
      }
      ["priority":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      int(8)
    }
    ["remote_title":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(0) ""
    ["remote_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6326 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(0) ""
    }
    ["source_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(1)
    ["suppress_filters":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    bool(true)
    ["target_content_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(0)
    ["target_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(3)
    ["type":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(10) "front_page"
  }
  [6]=&gt;
  object(Inpsyde\MultilingualPress\Common\Type\FilterableTranslation)#6324 (9) {
    ["icon_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6325 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(95) "http://stories-dev.required.ch/wp-content/plugins/multilingual-press/assets/images/flags/en.gif"
    }
    ["language":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage)#6323 (3) {
      ["is_rtl":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      bool(true)
      ["names":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      array(6) {
        ["english_name"]=&gt;
        string(7) "English"
        ["native_name"]=&gt;
        string(2) "EN"
        ["custom_name"]=&gt;
        string(0) ""
        ["text"]=&gt;
        string(2) "EN"
        ["http_name"]=&gt;
        string(5) "en-US"
        ["wp_locale"]=&gt;
        string(5) "en_US"
      }
      ["priority":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      int(10)
    }
    ["remote_title":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(0) ""
    ["remote_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6322 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(0) ""
    }
    ["source_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(1)
    ["suppress_filters":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    bool(true)
    ["target_content_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(0)
    ["target_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(6)
    ["type":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(10) "front_page"
  }
  [1]=&gt;
  &amp;object(Inpsyde\MultilingualPress\Common\Type\FilterableTranslation)#6320 (9) {
    ["icon_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6321 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(95) "http://stories-dev.required.ch/wp-content/plugins/multilingual-press/assets/images/flags/de.gif"
    }
    ["language":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage)#6319 (3) {
      ["is_rtl":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      bool(true)
      ["names":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      array(6) {
        ["english_name"]=&gt;
        string(6) "German"
        ["native_name"]=&gt;
        string(2) "DE"
        ["custom_name"]=&gt;
        string(0) ""
        ["text"]=&gt;
        string(2) "DE"
        ["http_name"]=&gt;
        string(5) "de-DE"
        ["wp_locale"]=&gt;
        string(5) "de_DE"
      }
      ["priority":"Inpsyde\MultilingualPress\Common\Type\AliasAwareLanguage":private]=&gt;
      int(4)
    }
    ["remote_title":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(0) ""
    ["remote_url":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    object(Inpsyde\MultilingualPress\Common\Type\EscapedURL)#6318 (1) {
      ["url":"Inpsyde\MultilingualPress\Common\Type\EscapedURL":private]=&gt;
      string(0) ""
    }
    ["source_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(1)
    ["suppress_filters":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    bool(true)
    ["target_content_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(0)
    ["target_site_id":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    int(1)
    ["type":"Inpsyde\MultilingualPress\Common\Type\FilterableTranslation":private]=&gt;
    string(10) "front_page"
  }
}
</pre></details>

**Comment by tfrommen** [comment]
@grappler is there some way/tool/channel we can use for direct communication? It seems you don't frequently the use the WPDE Slack (where I left a message last week)...? :)

**Comment by tfrommen** [comment]
Closed as the codebase was outdated. https://github.com/inpsyde/multilingual-press/commit/7cda81bfeb90d5da3144f5c8e74588c32bef97c9 fixed the issue at hand.
