### ISSUE TITLE
Chinese Language can't be set 

### ISSUE THREAD

**Issue by mahmoudkhalafallah** [inpsyde/multilingual-press#232]
#### Version Information
* WordPress: 4.5
* MultilingualPress: 2.4.7

#### Steps to Reproduce
1. add 2 sites the first is in English, and the Second has to be in Chinese.
2. while trying to add the Chinese version of your site, click save and wait for page reload.

#### What I Expected
The site language to be Chinese.

#### What Happened Instead
The site language is Chinese Singapore instead of Chinese.
as shown in the screenshot the value attribute sent from the select element is the same for both Chinese and Chinese Singapore (zh).

#### Screenshot or Video
![multilingualpress-bug](https://cloud.githubusercontent.com/assets/13049002/18616641/ecfb510a-7dbf-11e6-8dfb-9c3bb00afd81.jpg)

**Comment by tfrommen** [comment]
Hi there,

I just checked this, and yes, the entry for _Chinese (Singapore)_ is incorrect (and has the same HTTP code as Chinese). We will fix this in a future release.

To get your site running right now, you can edit the language in the Language Manager (to be found at `/wp-admin/network/settings.php?page=language-manager`). Find _Chinese (Singapore)_, edit the **HTTP** code to be `zh-SG`, and save the change.

Best regards,
Thorsten

**Comment by mahmoudkhalafallah** [comment]
Ok, thank you

**Comment by tfrommen** [comment]
Has been fixed for `master` in 49d2d923324a0b3e4b490f110584ae430d7d99ff.

**Comment by tfrommen** [comment]
Closed with https://github.com/inpsyde/multilingual-press/commit/43f64b13d74c8b5b31072b8e86ff24cfd8b6e990.
