### ISSUE TITLE
Languange Sites disappear completely

### ISSUE THREAD

**Issue by xxJulayaxx** [inpsyde/multilingual-press#238]
#### Version Information
- WordPress: WordPress 4.6.1
- MultilingualPress: Version 2.4.7
#### Steps to Reproduce
1. Go to German (main) page: http://www.travelling-treasures.com/
2. Click: Switch to English or Spanish
#### What I Expected

Load the page in the respective language. 
#### What Happened Instead

The page is non existing, does not load at all: 
http://es.travelling-treasures.com/
http://en.travelling-treasures.com/

This morning, I add a contact form to both DE and EN site and it still worked, I could check the changes on the English site. No I wanted to add the contact form for Spanish site and both English and Spanish sites are broken. I deactiveted the form plugin, (ninja forms) but still the pages don't show. I am not a programmer. 

Thanks for you help

**Comment by xxJulayaxx** [comment]
At first I could still enter the Dashboard from Wp-admin area, only I couldnt edit any post or site. But now not even the dashboard loads.

**Comment by tyrann0us** [comment]
All sites you mentioned are running well for me except`404` errors on your images. You need to configure your image CDN (https://jetpack.com/support/photon/) properly to support language sub domains. This probably has nothing to do with MultilingualPress.

**Comment by tfrommen** [comment]
Hi @xxJulayaxx (and also hi @tyrann0us - thanks for stepping in)! :)

For me, too, it's just like @tyrann0us described it. I can visit the front end of all three languages/sites, and I can also go to the login page. Images (except for theme-specific things, and Customizer stuff) are only displayed on the German (main) site (which WordPress.com told me was experiencing _connection problems_).

As I see it, there is no issue with MultilingualPress.

Can you provide more information?

**Comment by xxJulayaxx** [comment]
Hi @tyrann0us and @tfrommen thank you so much, seems they were just down last night, I can see them again now too. And also ty for you tip for the photos, I was wondering why that was as they sometimes show and sometimes not. I tried to activate Photon, which works fine for EN and ES, but  for DE it tells me this: photon failed to activate. error this module requires your site to be set to publicly accessible
Shuold I ask Jetpack for support on that, I guess? 

Thank you so much!

**Comment by tfrommen** [comment]
Hi @xxJulayaxx,

please have a look at `wp-admin/options-reading.php` of your german site. Untick the checkbox for search engine visibility, save, then try again Photon. If this still doesn't solve the issue, please go ahead and ask Jetpack, yes.
