### ISSUE TITLE
Media Library Grid View JS issue

### ISSUE THREAD

**Issue by luisarn** [inpsyde/multilingual-press#249]
* WordPress: 4.7.1 
* MultilingualPress: 2.5.0

1. Enable Multilingual Press 
2. Go to Media Library
3. Switch to Grid View

3rd party plugins that relies on Javascript stops working.
Seems the JS loaded again when entering Grid View (check console):

Uncaught Error: Backbone.history has already been started

**Comment by tfrommen** [comment]
Hi @luisarn,

thanks for reporting.

I had a look at it, and it seems this is an issue with WordPress core. I just created a [ticket on Trac](https://core.trac.wordpress.org/ticket/39612).

Regarding MultilingualPress: by default, there shouldn't be any MLP JavaScript running on _Media_. A quick fix would therefore be to find out why `admin.js` is enqueued, and undo that (taking care of all modules still being functional on their individual pages, of course).

I will look into this within the next two weeks or so.

Cheers,
Thorsten

**Comment by tfrommen** [comment]
Hi @luisarn,

while my Trac ticket is waiting to get merged (and eventually released), I fixed the asset loading in MLP.

If that is possible, you can try [the new branch](https://github.com/inpsyde/multilingual-press/tree/2.5). Ideal result: the MLP JavaScript is working where it should, and you can use the Media page. :)

**Comment by tfrommen** [comment]
Fixed in MultilingualPress v2.5.1.
