### ISSUE TITLE
Incorrect flags for some languages

### ISSUE THREAD

**Issue by bueltge** [inpsyde/multilingual-press#7]
The plugin is really great. I noticed that flags are shown incorrectly in the Multisite settings screen.
http://pokit.org/get/?a4a2f7527233324bf6967fd9636f5963.png

For example, my native language, Bosnian, has a flag of The Bahamas instead of Bosnia & Herzegovina. I believe the error occurred because of the different ISO codes for countries and languages. ISO code for Bosnian is 'bs' and for Bosnia it's 'ba'.
This only happens in settings. Flags are displayed correctly on the site.

_via http://wordpress.org/support/topic/plugin-multilingual-press-incorrect-flags-for-some-languages_

**Comment by Krislynde** [comment]
Old topic, I know. I am moving to the Multisite, using this wonderful plugin and discovered that wrong flag is also displayed for Estonian language. Plugin shows et.gif but the right flag is named ee.gif
