### ISSUE TITLE
Languages are duplicated on updates

### ISSUE THREAD

**Issue by 2ndkauboy** [inpsyde/multilingual-press#78]
On the mlp-site-settings page, all options in the select (except the first few already in use by a site) are duplicated.

![mlp-free-language-selection](https://cloud.githubusercontent.com/assets/1793177/4635138/bc4fce7e-53d6-11e4-8894-0123723d6c3c.png)
I am using MLP Version 2.1.1 with WordPress 4.0 in a subdomain setup.

**Comment by toscho** [comment]
This was a bug in our update routine. Will be fixed in the next release.
