### ISSUE TITLE
mlp_show_linked_elements broken; provides different results for logged in / out users

### ISSUE THREAD

**Issue by tordans** [inpsyde/multilingual-press#82]
I expect mlp_show_linked_elements() to show the same result for logged in and logged out users.
But in this example it shows 0 results for logged out users but the correct results for logged in users.
Note that all pages are published and public; so the rights/roles cannot be the reason for this.

This problem is tested with WP 4.0.1 and Multilingual Press Free 2.1.2.

Problem description:

**Logged in users (correct behavior):**
php:
```
  $config = array (
    'link_text'         => 'text',
    'show_current_blog' => FALSE,
    'echo'              => FALSE,
    'sort'              => 'priority',
    'strict'            => FALSE
  );
  var_dump(mlp_show_linked_elements( $config ));
```
result:
```
string(148) "<div class="mlp_language_box"><ul><li><a rel="alternate" hreflang="de-DE"  href="http://www.betterplace.dev/c/menschen/">Deutsch</a></li></ul></div>"
```

**Logged out users (false behavior):**
php:
```
// same
```
result:
```
string(0) ""
```

**Comment by toscho** [comment]
That happens when the sites are marked as _private_. See [this topic on wordpress.org](https://wordpress.org/support/topic/language-switcher-widget?replies=3), it includes a screenshot.

We will improve the UX for that, and maybe change it completely in one of the future versions.

**Comment by tordans** [comment]
Great, thanks @toscho those Multisites where in deed not "Public". It works now.
There very confusing part is, that logged in and logged out users behave differently again.
Having this more explicit would be great!
