### ISSUE TITLE
Add a pot file

### ISSUE THREAD

**Issue by fxbenard** [inpsyde/multilingual-press#83]
If I use makepot to create the pot - I have 80 strings
If I compare it with your de_DE.po - 200 strings
Didn't you included the pro translations in the free version?

**Comment by bueltge** [comment]
We have a central translation service for our products. It was so much fine, if you add you user to our translater list. Which language will you add?
http://translate.marketpress.com/projects/plugins/multilingualpress-pro

Register for the service: http://translate.marketpress.com/sign-up/

**Comment by fxbenard** [comment]
Oh great a Glotpress install. I have a fully reviewed French translation on my side.
But it doesn't mean you shouldn't remove your de-DE file from the languages folder, add a .pot instead and a nice readme text for people to join your GlotPress community ;)

**Comment by bueltge** [comment]
Currently we have a difference between relase and development, also in the language files. After release the new version we will add all full translation files, also french. There is 100% ready in glotpress.
http://translate.marketpress.com/projects/plugins/multilingualpress-pro

Your idea is fine. I think we add also the hint for the translation service via web, glotpress, to the readme.

**Comment by fxbenard** [comment]
Indeed my makepot is clearly different from your glotpress file ;)
Registered there, I'll have a deeper look to the translation

**Comment by bueltge** [comment]
Thanks a lot! :+1:  Now you can edit on the french translation of MLP
http://translate.marketpress.com/projects/plugins/multilingualpress-pro
