### ISSUE TITLE
Notice when MLP is used with BuddyPress

### ISSUE THREAD

**Issue by tfrommen** [inpsyde/multilingual-press#88]
>Notice: `bp_setup_current_user` was called incorrectly. The current user is being initialized without using `$wp->init()`. Please see Debugging in WordPress for more information. (This message was added in version 1.7.)

Call stack is as follows:

* `bp_setup_current_user()`
* `do_action('set_current_user')`
* `wp_set_current_user()`
* `get_currentuserinfo()`
* `wp_get_current_user()`
* `get_current_user_id()`
* `Mlp_User_Backend_Language->locale()`
* `apply_filters('locale')`
* `get_locale()`
* `load_plugin_textdomain()`
* `Multilingual_Press->load_plugin_textdomain()`
* `do_action('inpsyde_mlp_loaded')`
* `Multilingual_Press->setup()`
* `mlp_init()`
* `do_action('plugins_loaded')`

The problem is that MLP implicitly triggers `wp_set_current_user()`, while being at WordPress core action `plugins_loaded` (priority `0`). BuddyPress kicks in and would like to do some things to _whatever it is_, which seemingly is [available after `after_setup_theme`](https://github.com/buddypress/BuddyPress/blob/3f1ebf3cbb52fdc55f1d46589258290bfe94d1c4/src/bp-core/bp-core-dependency.php#L95-L110).

**Comment by toscho** [comment]
We cannot wait for `after_setup_theme` because then all the wrong language files from WordPress and plugins are loaded already.

**Comment by tfrommen** [comment]
@toscho came up with a bugfix for BuddyPress (as well as bbPress). He will test and eventually provide the according developers with it.

This issue will be closed as _wontfix_ now.
