### ISSUE TITLE
Deleting a site removes relationships from remaining sites

### ISSUE THREAD

**Issue by glueckpress** [inpsyde/multilingual-press#97]
### Replicate:

1. Create 2 sites
* set up site relationship between the 2
* create posts, pages, taxonomies and set relationship for those, __so you have 2 “translated” sites__
* __Create another site__ by cloning one of the exiting sites
* set up relationship with the 2 previously existing sites
* create posts, pages, taxonomies and set relationship for those, __so you now have 2 “translated” sites__
* delete site 3

## Expected result:

* Site 3 is deleted -> should just “disappear”.
* Site 2 and 3 and their relationships among each other should stay completely intact, just before step 4 from above.

## Observed result:

* The moment site 3 gets deletes, the relationship between site 1 and 2 is removed.
* Setting the relationship anew in Network Admin -> Sites -> Edit brings back most of the previous relationships between posts/pages.
* Previous relationships between taxonomies remain lost and have to be set anew manually.

**Comment by tfrommen** [comment]
Closed with 6258cba5c235535a3ddb499836b0248d916a5cb8.
